"""Script to orchestrate LLM-based generation of prepositional mismatches."""
import os
import json
import logging
from dotenv import load_dotenv
import sys
from typing import List, TypedDict, Dict, Any

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))
from src.utils.paths import PREP_MISMATCH_PATH
from src.utils.llm_client import ask_llm

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

SYSTEM_PROMPT: str = """
You are an expert Polish, Russian, and Ukrainian linguist specializing in L2 language acquisition and cross-lingual interference.
Your task is to generate a comprehensive list of prepositional government (rekcja przyimkowa) mistakes
and spatial preposition calques made by native Russian/Ukrainian speakers when speaking Polish.
"""

USER_PROMPT: str = """
Generate a highly exhaustive list of at least 60 VERB mistakes and 40 NOUN mistakes.
Focus on the most common traps: 'o' vs 'za', 'na' vs 'w', 'na' vs 'za', and zero-preposition drops.
Make sure the case abbreviation correctly matches the case that the *wrong* preposition would force.
"""


class PrepositionMistake(TypedDict):
    category: str  # "VERB" or "NOUN"
    polish_lemma: str
    correct_prep: str
    incorrect_prep: str
    case: str  # "nom", "gen", "dat", "acc", "inst", "loc", "voc"


def fetch_preposition_mismatches() -> List[dict]:
    """Fetches prepositional mismatches using the LLM client.

    Returns:
        The list of preposition mistakes.
    """
    result = ask_llm(
        system_prompt=SYSTEM_PROMPT,
        user_prompt=USER_PROMPT,
        temperature=0.3,
        max_tokens=8192,
        response_schema=list[PrepositionMistake],
    )
    return result if result else []


def main() -> None:
    """Generates and saves the preposition mismatches dataset."""
    generated_data = fetch_preposition_mismatches()

    if not generated_data:
        logging.error("No data was generated by any model.")
        raise RuntimeError(
            "Data generation for preposition mismatches failed. Halting pipeline."
        )

    formatted_data: Dict[str, Dict[str, Dict[str, list]]] = {
        "VERB_PREP_ERRORS": {},
        "NOUN_PREP_ERRORS": {},
    }

    for item in generated_data:
        try:
            category = item.get("category", "").upper()
            lemma = item.get("polish_lemma", "").lower()
            correct = item.get("correct_prep", "").lower()
            incorrect = item.get("incorrect_prep", "").lower()
            case = item.get("case", "").lower()

            cat_key = f"{category}_PREP_ERRORS"
            if cat_key not in formatted_data:
                continue
            if lemma not in formatted_data[cat_key]:
                formatted_data[cat_key][lemma] = {}
            formatted_data[cat_key][lemma][correct] = [incorrect, case]
        except Exception as e:
            logging.error(e)
            logging.warning(f"Skipping malformed entry: {item}")
            continue

    if not formatted_data["VERB_PREP_ERRORS"] and not formatted_data["NOUN_PREP_ERRORS"]:
        raise RuntimeError(
            "Data generation yielded no valid preposition rules. Halting pipeline."
        )

    verb_errors = formatted_data.get("VERB_PREP_ERRORS", {})
    noun_errors = formatted_data.get("NOUN_PREP_ERRORS", {})

    logging.info(
        f"Successfully generated {len(verb_errors)} verb mismatches and"
        f" {len(noun_errors)} noun mismatches."
    )

    os.makedirs(os.path.dirname(PREP_MISMATCH_PATH), exist_ok=True)
    with open(PREP_MISMATCH_PATH, "w", encoding="utf-8") as f:
        json.dump(formatted_data, f, ensure_ascii=False, indent=4)

    logging.info(f"Saved to {PREP_MISMATCH_PATH}")


if __name__ == "__main__":
    main()
